services:
  mysql:
    image: mysql:8.0
    container_name: fev_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
